### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by Devyatyi9** [erodozer/open-vt#5]
<details>
  <summary>Screenshot</summary>
  
  ![Image](https://github.com/user-attachments/assets/ab4c5a5b-974e-4cf9-84f5-af74ef1e0ed3)
  ![Image](https://github.com/user-attachments/assets/44323b3c-4c5f-4daf-8ed9-57913d7955e3)

</details>

I just wanted to select a model to view, but an error occurred. Now the application always writes this name in the log even after deleting it from the directory for models.
App from openvt-windows-nightly.zip

[godot.log](https://github.com/user-attachments/files/19821589/godot.log)

[godot2025-04-19T18.33.59.log](https://github.com/user-attachments/files/19821593/godot2025-04-19T18.33.59.log)

[godot2025-04-19T18.35.44.log](https://github.com/user-attachments/files/19821594/godot2025-04-19T18.35.44.log)

[godot2025-04-19T18.41.02.log](https://github.com/user-attachments/files/19821597/godot2025-04-19T18.41.02.log)

**Comment by erodozer** [comment]
You can try deleting the settings file, as it's probably crashing trying to load the model.

Does this model load properly in VTS?  Can you verify within the `.model3.json` file and the models textures directory that everything matches and is present?  Failing to load and image isn't common, but what immediately comes to mind is the possibility of the names not matching.  While Windows file systems aren't usually isn't case-sensitive, Godot's virtual filesystem appears to be.

**Comment by Devyatyi9** [comment]
![Image](https://github.com/user-attachments/assets/eef4c6bc-3151-4cd6-911b-6189b4e40b9c)

[Design_genius(1).model3.json](https://github.com/user-attachments/files/19832830/Design_genius.1.model3.json)

**Comment by erodozer** [comment]
Possibly, since it looks like your files might not have copied correctly.  If you open up `.model3.json` in a text editor, it'll have a section called FileReferences, eg.

```
	"FileReferences": {
		"Moc": "ero20.moc3",
		"Textures": [
			"ero20.2048/texture_00.png"
		],
		"Physics": "ero20.physics3.json",
		"DisplayInfo": "ero20.cdi3.json"
	},
```

That holds the names of other files it depends on relative to it.  If there's something wrong with the names, or they're missing, it could cause some problems stability issues with the Live2D extension.  I'll look into improving the behavior so it can be a soft failure instead of crash.

**Comment by Devyatyi9** [comment]
BTW, the model works in VTubeStudio/

![Image](https://github.com/user-attachments/assets/192551d7-0006-4d35-a1fe-937d4e9c62b3)

**Comment by erodozer** [comment]
the icon isn't the issue, as that has no bearing on the model loading and is already handled as a soft error.  An icon loading issue looks like this

```
E 0:00:02:061   model_panel.gd:24 @ _on_model_manager_list_updated(): Error opening file 'user://Live2DModels/pixel_ero_20/icon.PNG'.
  <C++ Error>   Condition "f.is_null()" is true. Returning: err
  <C++ Source>  core/io/image_loader.cpp:89 @ load_image()
  <Stack Trace> model_panel.gd:24 @ _on_model_manager_list_updated()
                model_manager.gd:49 @ refresh_models()
```

Please verify that the contents of the json match what's on your filesystem.  An image load error in this case indicates that there might be something wrong with the file names in the texture atlas folder.

**Comment by Devyatyi9** [comment]
<details>
  <summary>What else should I look into?</summary>
  
  ![Image](https://github.com/user-attachments/assets/2e9066a4-123c-4c89-9cd8-1008ef9abef5)

</details>

**Comment by erodozer** [comment]
Okay, I've pushed a few updates that hopefully will fix this, since your logs had several issues stemming from this model of yours.  Please download the latest build from itchio

A fallback icon will now be used, so that should reduce the noise of the menu.  You should no longer get in your logs
> ERROR: Error opening file 'user://Live2DModels/Design_genius_White/'.
   at: load_image (core/io/image_loader.cpp:89)
ERROR: Failed to load image. Error 12
   at: load_from_file (core/io/image.cpp:2554)

It appears that the crash causing load error might have been due to a bad animation, so I tried adding a fix to prevent this error
> ERROR: Found the key outside the animation range. Consider using the clean-up option in AnimationTrackEditor to fix it.

I also fixed crash on startup if the most recently loaded model has been deleted, so you'll no longer have to remove the settings.json

**Comment by Devyatyi9** [comment]
Hm, still crashes, but without error.
I see one warning

[godot.log](https://github.com/user-attachments/files/19840665/godot.log)

**Comment by erodozer** [comment]
A fresh download of the model is working fine for me in Linux, but is failing under Wine, so it's possibly something up with the compiled Live2D extension under Windows.

I'll look deeper, but know that Windows is not the primary supported platform for this software and will be more error prone.  If you're already on Windows it's best to continue using VTubeStudio unless you are fine with the instability and just want to test things.

**Comment by erodozer** [comment]
After testing I noticed that all model loading had broken recently for Windows builds.  I've rolled back the change as it wasn't anything critical and now model loading is working for me in Wine again.  Thanks to testing with that model, I've also tuned some settings to improve memory usage.

New builds have been pushed.
